///////////////////////////////////////////////////////////////////////////////
// Copyright (C) 2026 Jean-Philippe Steinmetz
// SPDX-License-Identifier: MPL-2.0
///////////////////////////////////////////////////////////////////////////////
import type { IconType } from "react-icons";
import {
    HiOutlineAcademicCap,
    HiOutlineBanknotes,
    HiOutlineBeaker,
    HiOutlineBellAlert,
    HiOutlineBolt,
    HiOutlineBookOpen,
    HiOutlineBriefcase,
    HiOutlineBuildingOffice2,
    HiOutlineCalendarDays,
    HiOutlineChartBar,
    HiOutlineChartPie,
    HiOutlineChatBubbleLeftRight,
    HiOutlineClipboardDocumentCheck,
    HiOutlineCloud,
    HiOutlineCog6Tooth,
    HiOutlineCreditCard,
    HiOutlineCube,
    HiOutlineCurrencyDollar,
    HiOutlineDocumentText,
    HiOutlineEnvelopeOpen,
    HiOutlineFolderOpen,
    HiOutlineFunnel,
    HiOutlineGlobeAlt,
    HiOutlineHeart,
    HiOutlineIdentification,
    HiOutlineInboxStack,
    HiOutlineKey,
    HiOutlineLifebuoy,
    HiOutlineLightBulb,
    HiOutlineMap,
    HiOutlineMegaphone,
    HiOutlineNewspaper,
    HiOutlinePaperAirplane,
    HiOutlinePhone,
    HiOutlinePhoto,
    HiOutlinePresentationChartLine,
    HiOutlinePuzzlePiece,
    HiOutlineQueueList,
    HiOutlineRectangleGroup,
    HiOutlineRocketLaunch,
    HiOutlineShieldCheck,
    HiOutlineShoppingCart,
    HiOutlineSparkles,
    HiOutlineSquares2X2,
    HiOutlineTag,
    HiOutlineTicket,
    HiOutlineTrophy,
    HiOutlineUserGroup,
    HiOutlineUsers,
    HiOutlineVideoCamera,
    HiOutlineWrenchScrewdriver,
} from "react-icons/hi2";

/** The icon a plugin nav item gets when its manifest names none, or one that isn't in `PLUGIN_ICONS`. */
export const DEFAULT_PLUGIN_ICON: IconType = HiOutlinePuzzlePiece;

/**
 * The `react-icons/hi2` icons a plugin manifest's nav `icon` can name. A fixed list rather than the whole icon set: importing every
 * icon by name would put all of them in the bundle. A plugin that needs another one gets it added here.
 */
export const PLUGIN_ICONS: Readonly<Record<string, IconType>> = {
    HiOutlineAcademicCap,
    HiOutlineBanknotes,
    HiOutlineBeaker,
    HiOutlineBellAlert,
    HiOutlineBolt,
    HiOutlineBookOpen,
    HiOutlineBriefcase,
    HiOutlineBuildingOffice2,
    HiOutlineCalendarDays,
    HiOutlineChartBar,
    HiOutlineChartPie,
    HiOutlineChatBubbleLeftRight,
    HiOutlineClipboardDocumentCheck,
    HiOutlineCloud,
    HiOutlineCog6Tooth,
    HiOutlineCreditCard,
    HiOutlineCube,
    HiOutlineCurrencyDollar,
    HiOutlineDocumentText,
    HiOutlineEnvelopeOpen,
    HiOutlineFolderOpen,
    HiOutlineFunnel,
    HiOutlineGlobeAlt,
    HiOutlineHeart,
    HiOutlineIdentification,
    HiOutlineInboxStack,
    HiOutlineKey,
    HiOutlineLifebuoy,
    HiOutlineLightBulb,
    HiOutlineMap,
    HiOutlineMegaphone,
    HiOutlineNewspaper,
    HiOutlinePaperAirplane,
    HiOutlinePhone,
    HiOutlinePhoto,
    HiOutlinePresentationChartLine,
    HiOutlinePuzzlePiece,
    HiOutlineQueueList,
    HiOutlineRectangleGroup,
    HiOutlineRocketLaunch,
    HiOutlineShieldCheck,
    HiOutlineShoppingCart,
    HiOutlineSparkles,
    HiOutlineSquares2X2,
    HiOutlineTag,
    HiOutlineTicket,
    HiOutlineTrophy,
    HiOutlineUserGroup,
    HiOutlineUsers,
    HiOutlineVideoCamera,
    HiOutlineWrenchScrewdriver,
};

/** The icon for a plugin nav item's `icon` name - see `PLUGIN_ICONS` - or `DEFAULT_PLUGIN_ICON`. */
export function pluginIcon(name: string | undefined): IconType {
    return (name && Object.prototype.hasOwnProperty.call(PLUGIN_ICONS, name) ? PLUGIN_ICONS[name] : undefined) ?? DEFAULT_PLUGIN_ICON;
}
